name: pandoc-sync
version: '0.1.0.0'
category: Web
author: Justin Le
maintainer: justin@jle.im
copyright: (c) Justin Le 2018
license: BSD3
github: mstksg/pandoc-sync
extra-source-files:
- README.md
dependencies:
- containers
- data-default
- directory
- filepath
- hslogger
- unordered-containers
- lens
- text
library:
  source-dirs: src
  ghc-options: -Wall
  # exposed-modules:
  # - Text.Pandoc.Sync
  # - Text.Pandoc.Sync.Format
  # - Text.Pandoc.Sync.File
  # - Text.Pandoc.Sync.Writer
  dependencies:
  - base >=4.7 && <5
  - aeson
  - base16-bytestring
  - binary
  - binary-orphans
  - bytestring
  - cryptohash-md5
  - dependent-sum
  - hashable
  - lens-aeson
  - megaparsec
  - pandoc-types
  - pandoc
  - psqueues
  - singletons
  - skylighting
  - time
  - transformers
  - type-combinators
  - witherable
  - free
  - operational
# executables:
#   pandoc-sync:
#     main: Sync.hs
#     source-dirs: app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     - -Wall
#     dependencies:
#     - base
#     - ansi-wl-pprint
#     - fsnotify
#     - optparse-applicative
#     - pandoc-sync
#     - yaml
